format = """
$python\
[](fg:#390080 bg:#769ff0)\
$directory\
[](fg:#769ff0 bg:#394260)\
$git_branch\
$git_status\
[](fg:#394260 bg:#212736)\
$time\
[ ](fg:#1d2230)\
\n$character"""

right_format = """
"""

[directory]
style = "fg:#ffffff bg:#769ff0"
format = "[ $path ]($style)"
truncation_length = 3
truncation_symbol = "…/"

[git_branch]
style = "bg:#394260"
format = '[[ $branch ](fg:#769ff0 bg:#394260)]($style)'

[git_status]
style = "bg:#394260"
format = '[[($all_status$ahead_behind )](fg:#769ff0 bg:#394260)]($style)'

[time]
disabled = false
time_format = "%R" # Hour:Minute Format
style = "bg:#1d2230"
format = '[[ $time ](fg:#a0a9cb bg:#1d2230)]($style)'

[python]
# By default, Starship shows the Python version if a `.py` file is present.
# This configures it to show the Python version and virtual environment when one is active.
style = "bg:#390080"
format = "[(${virtualenv})]($style)"
python_binary = "python3"
symbol = ""
pyenv_version_name = true

